const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  listPorts: () => ipcRenderer.invoke('list-ports'),
  connect: (port, baud) => ipcRenderer.invoke('connect', { port, baud }),
  disconnect: () => ipcRenderer.invoke('disconnect'),
  sendU8: (frameId, value) => ipcRenderer.invoke('send-u8', { frameId, value }),
  sendF32: (frameId, value) => ipcRenderer.invoke('send-f32', { frameId, value }),
  sendU16: (frameId, value) => ipcRenderer.invoke('send-u16', { frameId, value }),
  sendU32: (frameId, value) => ipcRenderer.invoke('send-u32', { frameId, value }),
  sendText: (frameId, text) => ipcRenderer.invoke('send-text', { frameId, text }),
  exitApp: () => ipcRenderer.invoke('exit-app'),
  getBrightness: () => ipcRenderer.invoke('get-brightness'),
  setBrightness: (percent) => ipcRenderer.invoke('set-brightness', { percent }),
  getVolume: () => ipcRenderer.invoke('get-volume'),
  setVolume: (percent) => ipcRenderer.invoke('set-volume', { percent }),
  getPlayChime: () => ipcRenderer.invoke('get-play-chime'),
  setPlayChime: (on) => ipcRenderer.invoke('set-play-chime', { on }),
  getPressureAlertSound: () => ipcRenderer.invoke('get-pressure-alert-sound'),
  setPressureAlertSound: (on) => ipcRenderer.invoke('set-pressure-alert-sound', { on }),
  getSettings: () => ipcRenderer.invoke('settings:get'),
  updateSettings: (patch) => ipcRenderer.invoke('settings:update', patch),
  getPatients: () => ipcRenderer.invoke('patients:list'),
  addPatient: (patient) => ipcRenderer.invoke('patients:add', patient),
  updatePatient: (payload) => ipcRenderer.invoke('patients:update', payload),
  removePatient: (id) => ipcRenderer.invoke('patients:remove', id),
  restorePatients: (payload) => ipcRenderer.invoke('patients:restore', payload),
  clearPatients: () => ipcRenderer.invoke('patients:clear'),
  listLogs: () => ipcRenderer.invoke('logs:list'),
  readLog: (name) => ipcRenderer.invoke('logs:read', name),
  checkUpdates: () => ipcRenderer.invoke('updates:check'),
  listPrinters: () => ipcRenderer.invoke('printers:list'),
  getPrinter: () => ipcRenderer.invoke('printers:get'),
  setPrinter: (name) => ipcRenderer.invoke('printers:set', name),
  printReport: (opts) => ipcRenderer.invoke('print:report', opts),
  exportReportPdf: (opts) => ipcRenderer.invoke('report:export-pdf', opts),
  exportReportData: (payload) => ipcRenderer.invoke('report:export-data', payload),
  listReports: (filter) => ipcRenderer.invoke('reports:list', filter),
  shareReport: (opts) => ipcRenderer.invoke('report:share', opts),
  removeReport: (name) => ipcRenderer.invoke('reports:remove', name),
  clearReports: () => ipcRenderer.invoke('reports:clear'),
  printReportPdf: (opts) => ipcRenderer.invoke('print:report-pdf', opts),
  login: (username, password) => ipcRenderer.invoke('auth:login', { username, password }),
  listAccounts: () => ipcRenderer.invoke('accounts:list'),
  addAccount: (account) => ipcRenderer.invoke('accounts:add', account),
  removeAccount: (payload) => ipcRenderer.invoke('accounts:remove', payload),
  resetAccountPassword: (payload) => ipcRenderer.invoke('accounts:reset', payload),
  logToMain: (payload) => ipcRenderer.send('logs:renderer', payload),
  playPromptSound: (key) => ipcRenderer.invoke('sound:play', { key }),
  testLed: () => ipcRenderer.invoke('led:test'),
  onSerialData: (cb) => ipcRenderer.on('serial-data', (_, payload) => cb(payload)),
  onConnectionChanged: (cb) => ipcRenderer.on('connection-changed', (_, connected) => cb(connected)),
  onPorts: (cb) => ipcRenderer.on('ports', (_, ports) => cb(ports)),
  onHeartbeatAck: (cb) => ipcRenderer.on('heartbeat-ack', (_, value) => cb(value)),
  onSystemState: (cb) => ipcRenderer.on('system-state', (_, value) => cb(value)),
  onAlarmState: (cb) => ipcRenderer.on('alarm-state', (_, value) => cb(value)),
  onStopTreatment: (cb) => ipcRenderer.on('stop-treatment', (_, value) => cb(value)),
  onShieldState: (cb) => ipcRenderer.on('shield-state', (_, value) => cb(value)),
  onModeCurves: (cb) => ipcRenderer.on('mode-curves', (_, value) => cb(value)),
});
